[tool.poetry]
name = "bittensor-api"
version = "0.1.0"
description = ""
authors = ["maneetgoyal <mgoyal@manufacanalytics.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
