[tool.poetry]
name = "api"
version = "0.1.0"
description = ""
authors = ["maneetgoyal <mgoyal@manufacanalytics.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.106.0"
uvicorn = {extras = ["standard"], version = "^0.25.0"}

[tool.poetry.scripts]
serve = "api.main:serve"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
